server:
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/we_play
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true