name: pull request workflow

on:
  pull_request:
    paths:
      - server/data-access/**
      - server/admin-api/**
      - server/data-migration/**
    branches:
      - develop
      
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          admin-api:
            - server/admin-api/**
          data-migration:
            - server/data-migration/**
    - if: steps.filter.outputs.foo == 'true'
      run: 'echo admin-api'
    - if: steps.filter.outputs.foo == 'true'
      run: 'echo data-migration'
